/**
 * Elemental contracts — the two directions a nation's identity reaches the
 * mission board.
 *
 *  SIGNATURE  contracts only your own element unlocks. This is what makes an
 *             Ember run read differently from a Tide one at the board, not just
 *             in the modifiers.
 *  DIPLOMATIC contracts generated by your standing with a specific village.
 *             Relations were previously something you READ; this is where they
 *             finally produce something you DO.
 *
 * Shaped exactly like the templates in constants.js / missionGen.js — `n, rk,
 * ryo, rep, dur, risk, mp, sq, spec` — so the existing board machinery, the
 * spec modifiers and the terrain layer all read them with no special case.
 *
 * Pure data + pure selectors. No G access. Unit-tested.
 */

/**
 * One signature contract per element per band, so the pool stays visible
 * without flooding the board. `spec` is deliberately the element's SIGNATURE
 * spec — these are the jobs you are called for because of who you are.
 */
export const SIGNATURE_MISSIONS = [
  // ── Fire · siege ─────────────────────────────────────────────────────────
  { el: 'Fire', n: 'Reopen the Cinder Pass',     rk: 'B', ryo: 7200,  rep: 9,  dur: 2, risk: 0.28, mp: 58,  sq: false, spec: 'siege',
    flavour: 'A rockfall has sealed the trade road. Someone has to unmake a mountain.' },
  { el: 'Fire', n: 'The Forge Wakes',            rk: 'A', ryo: 14500, rep: 19, dur: 3, risk: 0.40, mp: 92,  sq: true,  spec: 'siege',
    flavour: 'Reignite the dead volcano forge. The last crew who tried are still down there.' },
  // ── Water · recovery ─────────────────────────────────────────────────────
  { el: 'Water', n: 'The Drowned Ward',          rk: 'B', ryo: 6800,  rep: 10, dur: 2, risk: 0.24, mp: 54,  sq: false, spec: 'recovery',
    flavour: 'A flooded hospital wing, and forty people who cannot be moved quickly.' },
  { el: 'Water', n: 'Pull Them Back',            rk: 'A', ryo: 13800, rep: 20, dur: 3, risk: 0.36, mp: 88,  sq: true,  spec: 'recovery',
    flavour: 'A rival village has written off its own trapped squad. Tide has not.' },
  // ── Wind · stealth ───────────────────────────────────────────────────────
  { el: 'Wind', n: 'Nobody Was Ever Here',       rk: 'B', ryo: 7000,  rep: 9,  dur: 2, risk: 0.26, mp: 56,  sq: false, spec: 'stealth',
    flavour: 'Remove a ledger from a guarded vault and leave the dust undisturbed.' },
  { el: 'Wind', n: 'The Hollow Passage',         rk: 'A', ryo: 14000, rep: 18, dur: 3, risk: 0.38, mp: 90,  sq: true,  spec: 'stealth',
    flavour: 'Walk an entire squad through a fortified border. Without a sound, and without a body.' },
  // ── Earth · escort ───────────────────────────────────────────────────────
  { el: 'Earth', n: 'The Long Convoy',           rk: 'B', ryo: 6900,  rep: 9,  dur: 2, risk: 0.22, mp: 55,  sq: false, spec: 'escort',
    flavour: 'Six wagons, two hundred miles, and every bandit clan on the route watching.' },
  { el: 'Earth', n: 'Nothing Entrusted Is Lost', rk: 'A', ryo: 14200, rep: 19, dur: 3, risk: 0.34, mp: 89,  sq: true,  spec: 'escort',
    flavour: 'The daimyo\'s heir, across contested ground, with the route already leaked.' },
  // ── Lightning · combat ───────────────────────────────────────────────────
  { el: 'Lightning', n: 'End It Quickly',        rk: 'B', ryo: 7400,  rep: 10, dur: 1, risk: 0.30, mp: 60,  sq: false, spec: 'combat',
    flavour: 'A rogue unit is dug in and recruiting. Every week costs more than the last.' },
  { el: 'Lightning', n: 'One Strike',            rk: 'A', ryo: 15000, rep: 20, dur: 2, risk: 0.44, mp: 94,  sq: true,  spec: 'combat',
    flavour: 'One pass, one target, no second attempt. Tempest was built for this.' },
]

/**
 * Contracts generated by standing with a named village.
 *
 * `mood` gates them: 'hostile' appears when relations have soured, 'warm' when
 * they have not. `{village}` is substituted with the real village name so the
 * board names the actual party — a sabotage job reads as a grievance against
 * someone specific, not a generic errand.
 */
export const DIPLOMATIC_MISSIONS = [
  { mood: 'hostile', n: 'Salt the Wells of {village}',   rk: 'B', ryo: 8000,  rep: 8,  dur: 2, risk: 0.34, mp: 62, sq: false, spec: 'stealth',
    flavour: 'Their reservoirs feed three districts. They will know it was deliberate; they will not be able to prove who.' },
  { mood: 'hostile', n: 'Discredit the {village} Envoy', rk: 'B', ryo: 7600,  rep: 9,  dur: 2, risk: 0.30, mp: 58, sq: false, spec: 'intel',
    flavour: 'A career ends in a single evening, if the right ledger reaches the right table.' },
  { mood: 'hostile', n: 'Break the {village} Border Post', rk: 'A', ryo: 13200, rep: 17, dur: 3, risk: 0.44, mp: 88, sq: true, spec: 'siege',
    flavour: 'They built it on ground that was never theirs. Time to make the point in daylight.' },
  { mood: 'warm',    n: 'Joint Patrol with {village}',   rk: 'C', ryo: 4200,  rep: 7,  dur: 1, risk: 0.14, mp: 34, sq: false, spec: 'combat',
    flavour: 'Their captain has worked with ours before. It goes easier when it is not a first meeting.' },
  { mood: 'warm',    n: 'Escort the {village} Delegation', rk: 'B', ryo: 6600, rep: 11, dur: 2, risk: 0.20, mp: 52, sq: false, spec: 'escort',
    flavour: 'Bring them home intact and the treaty signs itself.' },
  { mood: 'warm',    n: 'Relieve the {village} Garrison', rk: 'A', ryo: 12800, rep: 18, dur: 3, risk: 0.36, mp: 86, sq: true, spec: 'recovery',
    flavour: 'They asked. That they asked at all is the important part.' },
]

/** Relation thresholds at which each mood's contracts become available. */
export const HOSTILE_BELOW = 30
export const WARM_ABOVE = 70

/** Signature contracts for an element. Empty for an unknown element. */
export function signatureMissionsFor(element) {
  return SIGNATURE_MISSIONS.filter(m => m.el === element)
}

/** 'hostile' | 'warm' | null for a relation value. */
export function moodFor(rel) {
  const r = rel ?? 50
  if (r < HOSTILE_BELOW) return 'hostile'
  if (r > WARM_ABOVE) return 'warm'
  return null
}

/**
 * Diplomatic contracts available against one village, with `{village}`
 * substituted. Returns [] when relations are unremarkable — most of the time
 * nothing should be on offer, or the board fills with grievances.
 */
export function diplomaticMissionsFor(village) {
  const mood = moodFor(village?.rel)
  if (!mood || !village?.n) return []
  return DIPLOMATIC_MISSIONS
    .filter(m => m.mood === mood)
    .map(m => ({ ...m, n: m.n.replace('{village}', village.n), village: village.n }))
}
